### ISSUE TITLE
Only translate first select line in pdf when select multi lines.

### ISSUE THREAD

**Issue by 404cn** [lsnow/translate-clipboard#13]
![Screenshot from 2022-06-21 16-09-23](https://user-images.githubusercontent.com/24653356/174749653-6caf48b0-a9c3-4c4d-9950-4b93e979a5a5.png)

**Comment by lsnow** [comment]
https://github.com/lsnow/translate-clipboard/commit/81adb49cdd3fd283a12179a43f4d5b88512d9cc5
