### ISSUE TITLE
please support RTL language

### ISSUE THREAD

**Issue by Ja7ad** [lsnow/translate-clipboard#9]
Hi
Please support RTL language.

![Screenshot from 2021-11-04 09-04-54](https://user-images.githubusercontent.com/56496801/140263351-f34d1ee6-bccb-4ead-b48d-943827991c03.png)

**Comment by lsnow** [comment]
Fixed.
But i don't know if it is correct.

**Comment by Ja7ad** [comment]
> Fixed. But i don't know if it is correct.

I checking now, but don't currently work for RTL

**Comment by lsnow** [comment]
The text typesetting is done by clutter, and I don’t know why it’s wrong.
Sorry, I can't help you😔
